# Generated by Django 5.1.6 on 2025-03-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_sell_book', 'Can sell book'), ('can_buy_book', 'Can buy book'), ('can_publish_book', 'Can publish book')]},
        ),
    ]
