# Generated by Django 5.1.6 on 2025-02-26 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add book'), ('can_delete_book', 'Can delete book'), ('can_change_book', 'Can change book')]},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='relationship_app.author'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
